### ISSUE TITLE
When transitioning between pages, previous page scrolls up before transitioning 

### ISSUE THREAD

**Issue by nukulb** [blackberry/jQueryMobile-BB10-Theme#1]

**Comment by ProLove365** [comment]
What browser are you using to view your app? Have you tested the code in Ripple?
As I started playing around with the new code, I noticed the .action-bar-overflow.tabs panel flickers on the screen of a Chrome browser as I use the Back button to leave a page with the cover transition. I uploaded the code to my hosting account and the same code looks and feels great on a BlackBerry 9930 and PlayBook 2.0. The screen transitions are very smooth.

**Comment by nunodonato** [comment]
Trying the kitchen sink in the dev alpha, I can't replicate this.

**Comment by nukulb** [comment]
I will put my example soon
~Nukul

**Comment by jasondscott** [comment]
This issue is a jQuery Mobile issue and not an issue specific to the theme. 
This is done for performance reasons.
If you want you can file an issue at https://github.com/jquery/jquery-mobile/issues
