### ISSUE TITLE
Duplicate Dropdowns when not using JQM-all

### ISSUE THREAD

**Issue by bobbyboy1999** [blackberry/jQueryMobile-BB10-Theme#108]
Hi,

Using the following files:

jquery 1.6.4
blackberry jqm init
jquery mobile 1.3
blackberry jqm

my dropdowns would duplicate (ie. there were two separate dropdown menus).  One menu was clearly the regular JQM, although the options were not present.  The next dropdown was the BB10 JQM which had all the options and seemed to work correctly.  When I replaced the above files with the JQM-all file, everything seemed to work fine.

I know this is BlackBerry's intent (ie. that we use JAM-all) as it is beautifully optimized for that.  However, I was hoping to be able to use the regular files as listed above as well.  It could simply be the versions I was using, however I thought that JQM 1.3 was OK to use.  If not, is there somewhere that lists the JQuery and JQM files that work properly with JQM init and BB JQM

Thanks to the team for all of their fantastic work.  It is truly an excellent project.

**Comment by jasondscott** [comment]
#104 should fix the problem for you.
Please let us know if you are still experiencing issues.
Thanks for the post!
