### ISSUE TITLE
Issues when used with phonegap for Android

### ISSUE THREAD

**Issue by ajmalmsali** [blackberry/jQueryMobile-BB10-Theme#110]
Graphical problems in Tabs
Active tab color appears white.
Everything ZOOMed..

**Comment by mdabydeen** [comment]
@ajmalmsali what version of PhoneGap are you using? I used PhoneGap recently and did not have this issue.

**Comment by ajmalmsali** [comment]
@mdabydeen the latest one, 2.5.0,
its my academic project, the things go smooth in android browser,
but when it is compiled as an app, everything goes wrong, its even too slow now,
and the same happens when the android app is ported to bb10.

**Comment by ajmalmsali** [comment]
https://github.com/blackberry/jQueryMobile-BB10-Theme/pull/104/files

had happend to see .ui-android-2x-fixed in src/lib/jquery.mobile.structure.css.
can't build the src, as grunt package.json must be edited for 0.4 to work.

**Comment by jasondscott** [comment]
This seems more like an android/phonegap issue not a BlackBerry 10 theme issue.
If not please provide jsfiddle of the problem you are experiencing
