### ISSUE TITLE
Need Help with actionbar tabs in android

### ISSUE THREAD

**Issue by ajmalmsali** [blackberry/jQueryMobile-BB10-Theme#111]

**Comment by mdabydeen** [comment]
@ajmalmsali anything more specific? perhaps a code sample?

**Comment by jasondscott** [comment]
Thanks for the post.
This is more of a question than an issue. You should direct this to the forums.
http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/bd-p/browser_dev

**Comment by ajmalmsali** [comment]
Tnx for the reply
Ajmal M Sali
Architect, Infohe - Information Hosting Expert
www.infohe.com
