### ISSUE TITLE
Future?

### ISSUE THREAD

**Issue by thtro** [blackberry/jQueryMobile-BB10-Theme#138]
Hi,
Is this theme still supported? I see no commits since a long time ago..
Is is going to be updated to JQM 1.4? Any roadmap?

**Comment by kwallis** [comment]
Unfortunately we have been concentrating on our implementation of BlackBerry 10 in Apache Cordova and our upcoming release of BlackBerry WebWorks. I hope we might be able to look at this theme again soon, but we have no firm timelines for it, unfortunately.

**Comment by thtro** [comment]
Thanks for being honest. JQM BB10 Theme is really good because it allows to port very easily apps from other platforms.
