### ISSUE TITLE
event is undefined in _setHeader of the dropdown

### ISSUE THREAD

**Issue by jcreamer898** [blackberry/jQueryMobile-BB10-Theme#23]
For whatever reason, I am using the dropdown and the event here... `item = $(event.target);` is undefined. It appears as though the item variable is unused anyways, so perhaps it should just be removed?

``` js
_setHeader: function(text) {
    var headerText = this.header.find('.ui-btn-text'),
            headerStatusText = headerText.find('.ui-collapsible-heading-status'),
            item = $(event.target);

    //Check if the content has been enhanced yet
    if(headerText.length === 0){
        this.header.text(text);
    } else {
        headerText.text(text).append(headerStatusText);
    }
},
```

**Comment by RedWolves** [comment]
To clarify,  no event seems to be passed in and is erring as undefined.  Additionally item doesn't seem to be used.  Talked with Jason Scott at the jQuery Developer Summit and we are going to remove that line.
