### ISSUE TITLE
$('[data-role="content"]').empty(); breaks Overflow menu

### ISSUE THREAD

**Issue by Gerii** [blackberry/jQueryMobile-BB10-Theme#33]
Emptying the content div breaks the overflow menu because the overflow menu is a child of the content div and will therefore be deleted when calling $('[data-role="content"]').empty();

**Comment by jasondscott** [comment]
Hi @Gerii
What would you expect to happen?

Thanks

**Comment by Gerii** [comment]
I would expect the overflow menu not to be part of the content div, so that the overflow menu doesn't stop working when calling the empty function on that div.
If that's not possible it should be mentioned in the readme so that other developers know that this breaks the actionbar.

**Comment by jasondscott** [comment]
@Gerii #39 should fix the problem for you. Thanks for submitting. If this does not fix your issue please open the issue again :smile:
