### ISSUE TITLE
When i sign app for Blackberry 10 "<input  type="date">" does not work

### ISSUE THREAD

**Issue by bornalibertines** [blackberry/jQueryMobile-BB10-Theme#38]
Jason is it `"<input  type="date">"` sported in Blackberry 10 Alfa?
It is working on Tablet.
Please let me know. Thanks

**Comment by bornalibertines** [comment]
Looked around and find that Blackberry 10 webworks sdk dosnt support <input type="date">

**Comment by jasondscott** [comment]
@astanley Can you comment on this?

**Comment by jasondscott** [comment]
@boriskol it should be working. Try updating your device/simulator and sdk to the latest. If it is still not working for you please log an issue here https://github.com/blackberry/BB10-WebWorks-Framework/issues
