### ISSUE TITLE
How to disable the Zoom for the user?

### ISSUE THREAD

**Issue by ghost** [blackberry/jQueryMobile-BB10-Theme#54]
Hi, how can I disable the zoom for the user?
If I use: <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
the scaling on my DevAlpha is destroyed and I see the actionbar very small.

**Comment by Gerii** [comment]
Just add the script from this knowledge base article to the header of your index site.
http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/How-to-set-up-the-viewport-for-a-BlackBerry-WebWorks-application/ta-p/1943807

<head>
    <script>
       var meta = document.createElement("meta");
       meta.setAttribute('name','viewport');
       meta.setAttribute('content','initial-scale='+ (1/window.devicePixelRatio) + ',user-scalable=no');
       document.getElementsByTagName('head')[0].appendChild(meta);
   </script>
</head>

**Comment by ghost** [comment]
Thank you
