### ISSUE TITLE
Dialog looks really bad

### ISSUE THREAD

**Issue by ghost** [blackberry/jQueryMobile-BB10-Theme#57]
Hi, is there any alternative for the dialog of jQueryMobile?
Because with this theme it looks not very well.

**Comment by Gerii** [comment]
Yes, the JavaScript functions alert, prompt and confirm.
http://www.w3schools.com/js/js_popup.asp
Or if you need more options to customize the dialog you can use the dialog class of WebWorks: https://developer.blackberry.com/html5/apis/blackberry.ui.dialog.html

**Comment by ghost** [comment]
thank you very much!
