### ISSUE TITLE
Issues with tabs in actionbar

### ISSUE THREAD

**Issue by ajmalmsali** [blackberry/jQueryMobile-BB10-Theme#60]
Tabs already showed in action bar, is again showed in the overflow menu.

**Comment by ajmalmsali** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>SV-Talk</title>
    <link rel="stylesheet" href="css/BlackBerry-JQM-all.css" />
    <script src="js/BlackBerry-JQM-all.js"></script>
</head>

<body>

<div data-role="page" id="events">
    <div data-role="header" data-theme="c" data-position="fixed"><h1>Events</h1></div>
    
    <div data-role="content">  
    </div>
    
    <div data-role="footer" data-position="fixed">
        <div id="action-bar-area" data-role="actionbar">
            <div id="t1" data-role="tab">
                <img src="generic_81_81_placeholder.png" alt="" />
                <p>Events</p>
            </div>
            <div id="t2" data-role="tab" href="#villagers">
                <img src="generic_81_81_placeholder.png" alt="" />
                <p>Villagers</p>
            </div>
            <div id="t3" data-role="tab">
                <img src="generic_81_81_placeholder.png" alt="" />
                <p>News</p>
            </div>
            <div id="t4" data-role="tab" data-overflow="true">
                <img src="generic_81_81_placeholder.png" alt="" />
                <p>Ideas</p>
            </div>
            <div id="t5" data-role="tab" data-overflow="true">
                <img src="generic_81_81_placeholder.png" alt="" />
                <p>Projects</p>
            </div>
            <div id="t6" data-role="tab" data-overflow="true">
                <img src="generic_81_81_placeholder.png" alt="" />
                <p>Forums</p>
            </div>
            <div id="sva1" data-role="action" data-overflow="true">
                <img src="generic_81_81_placeholder.png" alt="" />
                <p>Logout</p>
            </div>
            <div id="sva2" data-role="action" data-overflow="true">
                <img src="generic_81_81_placeholder.png" alt="" />
                <p>About</p>
            </div>
        </div>
       
    </div>
</div>

</body>
</html>

**Comment by mdabydeen** [comment]
Not sure what you are trying to say here. Is it possible to post your code/example on [JSBIN](http://www.jsbin.com) or a similar website?

**Comment by ajmalmsali** [comment]
http://jsbin.com/izepiy/1/edit, i will show a snapshot of the problem soon..

**Comment by ajmalmsali** [comment]
that was an issue with my browser, i guess, got expected out in ripple.
