### ISSUE TITLE
Page Links not working..

### ISSUE THREAD

**Issue by ajmalmsali** [blackberry/jQueryMobile-BB10-Theme#61]
on clicking events/villagers tab, the page is not changed

<div data-role="page" id="events">
.
.
.
<div data-role="tab" data-overflow="false" href="#villagers">
                <img src="generic_81_81_placeholder.png" alt="" />
                <p>Villagers</p>
</div>

</div>

<div data-role="page" id="villagers">
.
.
.
<div data-role="tab" data-overflow="false" href="#events">
                <img src="generic_81_81_placeholder.png" alt="" />
                <p>events</p>
</div>

</div>

**Comment by mdabydeen** [comment]
is this the same issue as #60 ?

**Comment by ajmalmsali** [comment]
Na not, the problem is, i cant specify, links to the tabs in action bar, 

http://jsfiddle.net/XpFMe/

**Comment by ajmalmsali** [comment]
worked with bind,
http://jsfiddle.net/jUwYw/
