### ISSUE TITLE
Actionbar and keyboard

### ISSUE THREAD

**Issue by Gerii** [blackberry/jQueryMobile-BB10-Theme#62]
When clicking into a textfield, the keyboard comes up and the actionbar moves over the keyboard. When using my app in landscape this hides the textfield. I know that I can move the page to bring it into view via JS, but it still leaves very little room for the user to input text.
So is there a way to keep the actionbar at the bottom of the screen (beneath the keyboard)?

**Comment by RedWolves** [comment]
Is this documented anywhere?  I spent a couple of hours helping someone debug their code trying to figure out why Title and Action bar was disappearing.
