### ISSUE TITLE
Content formatting is too small

### ISSUE THREAD

**Issue by Magneticdud** [blackberry/jQueryMobile-BB10-Theme#63]
The size of h1 h2, paragraph and so on are too small compared to headers and the rest, the text will appear almost unreadable on the high definition dev alpha display

**Comment by Magneticdud** [comment]
Adding font-size: 3em; to line 4502 in \kitchenSink\lib\BlackBerry-JQM-all.css makes stuff looks better.

I'm a newbie so I have no idea how to fork and request a pull nor I want to lose 2 hours to understand how git works.

**Comment by mdabydeen** [comment]
I think 3em is too big, 2em looks much better.

**Comment by mdabydeen** [comment]
@jasondscott your thoughts on this, please.

**Comment by Magneticdud** [comment]
I feel that with 2em the content it's too small compared with the other menus. It's barely readable on the Dev Alpha screen (can be read, but compared with the huge header size, looks very small, in my opinion)

**Comment by jasondscott** [comment]
Hi @Magneticdud

In the meantime you can use custom css to make your content any size you want for your app. 
Include it after the BB10 css file.

Thanks for your post.

**Comment by jasondscott** [comment]
@Magneticdud New font sizes should be big enough. Please let me know if you see any that are still too small.

Thanks for the post.
