### ISSUE TITLE
The theme does not work in BB10 apps?

### ISSUE THREAD

**Issue by Magneticdud** [blackberry/jQueryMobile-BB10-Theme#64]
When I pack my app as a BB10 app, I get this error:

![error](http://i.stack.imgur.com/VRo9d.png)
http://i.stack.imgur.com/VRo9d.png

It looks like the spinner png in base64 is giving an error

**Comment by Magneticdud** [comment]
I might try to replace all the embedded png with real png, but there are 106 occurrencies...

**Comment by Magneticdud** [comment]
Fixed, the minimum SDK version to have it working is 1.0.3.8
I had 1.0.2

**Comment by jpeszleny** [comment]
I had the same error to and finally came across this post. Thanks for your solution. The 1.0.2 sdk defiantly has issues with the jQuery Mobile BB10 theming.
