### ISSUE TITLE
jQM theme misbehaves when used within WebWorks v1.0.3.8

### ISSUE THREAD

**Issue by astanley** [blackberry/jQueryMobile-BB10-Theme#65]
Developer reporting that the theme does not behave as expected when packaged within a BlackBerry 10 app, compiled using WebWorks v1.0.3.8.

http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/Blackberry-WebWorks-1-0-3-8-and-Blackberry-jQuery-mobile/td-p/2017367

Reported issues:
- Actionbar tab menu appears white
- data themes not being recognized

Are others seeing this as well?  I've asked for web inspector console data.

**Comment by Gerii** [comment]
No, works fine for me.

**Comment by Magneticdud** [comment]
I had the opposite problem, it wasn't working compiling with webworks 1.0.2, is working now with 1.0.3.8

**Comment by mdabydeen** [comment]
@astanley can't reproduce this.

**Comment by jasondscott** [comment]
Hi @astanley 
I am not able to reproduce this.
Can you let me know if this is still an issue with SDK 1.0.4.5 and the latest version of the theme?
