### ISSUE TITLE
Action-bar / Jquery changePage not working

### ISSUE THREAD

**Issue by itassets** [blackberry/jQueryMobile-BB10-Theme#67]
The code below is not working. The project is a jquerymobile using bb10-theme.
The only changepage is executed is #openAboutPage which a single .html within the project and it is show as a dialog. The action bar in the footer shows the icons and looks to be ok but clicking on main, customer or contactus doesnt execute the changePage. Any clue?

```
<div data-role="footer" data-position="fixed">
  <div data-role="actionbar">
    <div id="o1" data-role="tab">
        <img src="logo/thumbs/icons/main.png" alt="" />
        <p>List</p>
    </div>
    <div id="o2" data-role="tab">
        <img src="logo/thumbs/icons/customer.png" alt="" />
        <p>Compose</p>
    </div>
    <div id="o4" data-role="action">
        <img src="logo/thumbs/icons/help.png" alt="" />
        <p>Help</p>
    </div>
    <div id="o5" data-role="action">
        <img src="logo/thumbs/icons/contactus.png" alt="" />
        <p>Contact us</p>
    </div>
  </div>
    <script type="text/javascript">
        $('[data-role="action"]').bind("vclick", function() {
           alert(this.id + " Clicked"); 
          switch (this.id) {
            case "o4":
              $.mobile.changePage( '#openAboutPage');
              break;
            case "o5":
              $.mobile.changePage( '#contactus');
              break;
          } 
        });
        $('[data-role="tab"]').bind("vclick", function() {
           alert(this.id + " Clicked"); 
          switch (this.id) {
            case "o1":
              $.mobile.changePage( '#main');
              break;
            case "o2":
              $.mobile.changePage( '#customer');
              break;
          } 
        });
    </script>
```

   </div>

**Comment by itassets** [comment]
Completing the code there is a 
    $(document).bind( 'pagebeforechange', function( event, data ) {
      .....
     url = parseUrl.....

```
case url

   case "#customer":
     ...
     ...
         $("#customer div:jqmData(role=content)").empty();
         $("#customer div:jqmData(role=content)").append (updated_content);
         $('#customer').trigger( "create" );
         break;
```

  }

I've had inspected the code and it is executed completely but the page isn't shown.

I'm using 
    <link rel="stylesheet" href="BlackBerry-JQM-all.min.css" />
    <script src="BlackBerry-JQM-all.min.js"></script>

not reference to a jquery libraries as i've read it is not necessary.

**Comment by mdabydeen** [comment]
@itassets are you using the latest update of the jQueryMobile-BB10-Theme?

**Comment by Gerii** [comment]
I also had the same problem. I solved it by moving header, content and footer div from the index to a separate file.
In the index I only have jQueryMobile, WebWorks and a script that waits for both of them to finish loading and then changes the page to my main content (and also some other listeners that shouldn't load more than one time).
If you need a sample just let me know.

**Comment by Gerii** [comment]
It may also work if you just wait for those two to finish loading and then set the listeners for the click event.

**Comment by jasondscott** [comment]
@itassets How and where do define the pages (#main, #customer, #contactus, #openAboutPage) all within the same html as the above code? or in separate html files for each?

**Comment by itassets** [comment]
Everything is the main.html but openAboutPage which is in help.html
All javascript code for events is in main.html including the bind for pagebeforechange which for openAboutPage the only thing i do is to set data.options.role = "dialog";for the customer a dinamic listview (tslcontent) is created and then
              $("#customer div:jqmData(role=content)").empty();
              $("#customer div:jqmData(role=content)").append (tslcontent);
              $('#customer').trigger( "create" );

all code is executed but the page is not render

**Comment by itassets** [comment]
Hi
  thanks for the comments. I've tried your solution. Doesnt work. Can you send me an example?
  I can make it works using  

data.toPage = "customer.html";

 but the data-role="content" which i'm populating in the pagebeforechange is not populated. 

 All js code is in main.html.

 Thanks in advance

Daniel

---

De: Gerii [mailto:notifications@github.com] 
Enviado el: Miércoles, 12 de Diciembre de 2012 06:29 a.m.
Para: blackberry/jQueryMobile-BB10-Theme
CC: Daniel
Asunto: Re: [jQueryMobile-BB10-Theme] Action-bar / Jquery changePage not working (#67)

I also had the same problem. I solved it by moving header, content and footer div from the index to a separate file. 
In the index I only have jQueryMobile, WebWorks and a script that waits for both of them to finish loading and then changes the page to my main content (and also some other listeners that shouldn't load more than one time). 
If you need a sample just let me know. 

—
Reply to this email directly or view  https://github.com/blackberry/jQueryMobile-BB10-Theme/issues/67#issuecomment-11282059 it on GitHub. 

  https://github.com/notifications/beacon/W5XqTCzQLpNF4gCq0jzovVLqdLPMpnv8rxvieSjw1g7qf_ypeQPmUsXDyB4IhGu_.gif

**Comment by jasondscott** [comment]
Hi Daniel,

Try this http://jsbin.com/ojugal/3/edit 
It seems to be working for me. 
I am going to close this issue, we can open it back up if it still isn't working for you.

Thanks for the post,

Jason
