### ISSUE TITLE
App shows up as a white screen on the BB10 Alpha Simulator 

### ISSUE THREAD

**Issue by jpeszleny** [blackberry/jQueryMobile-BB10-Theme#68]
So I have this problem where I keep getting a white screen for my app on the BB10 simulator. After a lot of debugging I found it has to do with my JavaScript file for my app. As soon as there's any referencing or functions that have to do with Web SQL my app doesn't work. It's just a blank white screen on the simulator. If I comment any of the code out that has to do with Web SQL the app shows up just fine.

So it has to be something to do with web works. It's not recognizing any of the Web SQL functions.

This is what my included JavaScript and CSS files look like for the head section on a page. 

<head>
    <title></title>

```
<link rel="stylesheet" media="screen" href="css/main.css" />
<link href="css/BlackBerry-JQM-all.css" rel="stylesheet" type="text/css" />
<script src="js/BlackBerry-JQM-all.js" type="text/javascript"></script>
<script type="text/javascript" src="local:///chrome/webworks.js"></script>
<script src="js/main.js" type="text/javascript"></script>  
```

</head>

If I try to just include this JavaScript below in my app I get the blank white screen.

var trainXDb = openDatabase('trainXDb', '1.0', 'TrainX DB', 50 \* 1024 \* 1024);

I am not sure where to go from here because I know where the problem is but have no way about solving it.

Any help would be much appreciated. 

Thanks!

**Comment by mdabydeen** [comment]
@jpeszleny can you provide some more details, what version of SDK and Simulator you are using etc.

**Comment by mdabydeen** [comment]
@jpeszleny is there a sample code you can send me with this?

**Comment by jpeszleny** [comment]
Hi, sorry for not replaying sooner. I did solve this problem and it had to do with a web SQL error.
