### ISSUE TITLE
Form element Select menus: select via Javascript

### ISSUE THREAD

**Issue by miamon** [blackberry/jQueryMobile-BB10-Theme#69]
Trying to select via value with this:

<pre><code>$('select#select-choice-0').val('express');
$('#select-choice-0').selectmenu();
$('#select-choice-0').selectmenu('refresh');
</code></pre>

and the result is:
![selectjavascript](https://f.cloud.github.com/assets/986605/9454/031b8488-44ac-11e2-89f1-7eb812c329c6.png)

tested with normal  JQueryMobile  and this code works fine.

So I think it's a jQueryMobile-BB10-Theme issue.

Or exist another method?

i am using:
blackberryjqm/BlackBerry-JQM-all.min.css
blackberryjqm/BlackBerry-JQM-all.min.js

and latest DevAlpha OS and WebWorks SDK

**Comment by jasondscott** [comment]
Hi @miamon 
Thanks for your post.
The select menu in the BB10 theme is different than the one in JQM. This was done to achieve the inline downdown effect (similar to native) instead of the popup version that JQM uses. 
This should fix your issue. I have added this to the documentation. 

```
$('select#select-choice-0').val('express');
$('#select-choice-0').dropdown();
```
