### ISSUE TITLE
Collapsible Content Blocks and dynamic content

### ISSUE THREAD

**Issue by Gerii** [blackberry/jQueryMobile-BB10-Theme#73]
If I update my Collapsible Content Block with new content, it looks like this: 
![IMG_00000217](https://f.cloud.github.com/assets/1199721/17659/9ba05c28-4881-11e2-9eb4-6aae9815c5ec.png)

Am I doing something wrong? Here's my code:

http://jsbin.com/eyidew/2/edit

**Comment by jasondscott** [comment]
Hi @Gerii 

This looks like an issue with jquery mobile, and not specifically the theme.
Could you create an issue there instead without the BB10 theme? https://github.com/jquery/jquery-mobile/issues 

In the meantime you can do this 

```
$('#infosRecording .ui-collapsible-content').empty();
$('#infosRecording .ui-collapsible-content').html(infos);
```
