### ISSUE TITLE
ActionBar not working at all

### ISSUE THREAD

**Issue by PhilipKirkbride** [blackberry/jQueryMobile-BB10-Theme#74]
I just went to the live demo turned on the Ripple Emulator and went to the ActionBar page. Doesn't seem to be working at all.

**Comment by mdabydeen** [comment]
Hi @PhilipK-ca This works for me. Are you using Ripple as a Chrome extension?

**Comment by PhilipKirkbride** [comment]
![Screen Shot 2012-12-17 at 10 21 32 PM](https://f.cloud.github.com/assets/835191/18561/233c3a18-48c2-11e2-9eee-653223560516.png)

Yes using the Chrome extension.

**Comment by mdabydeen** [comment]
Can you elaborate more on what isn't working?

**Comment by PhilipKirkbride** [comment]
Cant you see the screenshot?

**Comment by PhilipKirkbride** [comment]
Oh I see it's several actionbars in a row. Sorry misunderstanding, the page has changed a lot since I last checked and thought this was a glitch.
