### ISSUE TITLE
Javascript UnCheck Methods Don't Work

### ISSUE THREAD

**Issue by PhilipKirkbride** [blackberry/jQueryMobile-BB10-Theme#76]
Have tried several ways to uncheck the JQMobile check boxes with Javascript, none seem to work.

1.
$('input[name=checkbox]').attr('checked', false);

2.
$("input[type='checkbox']").checkboxradio('disable');

3.
$("input[type='checkbox']").attr("checked",false).checkboxradio("refresh");

Methods 2 & 3 return the following the Javascript Console. 

TypeError: Object [object Object] has no method 'checkboxradio'

**Comment by jasondscott** [comment]
When I run follow on kitchensink/checkboxes.html all of the items are checked.

```
$('input[type=checkbox]').attr('checked', true);
$("input[type='checkbox']").checkboxradio("refresh");
```

Do you have a jsfiddle or jsbin with some sample code?

**Comment by PhilipKirkbride** [comment]
It seems the problem is actually something to do with the Ripple Emulator if I go into kitchenshink/checkboxes.html and run the command you posted it works. If you turn the Ripple Emulator on it returns "TypeError: Object [object Object] has no method 'checkboxradio'". 

I packaged the code and tested on DevAlpha and it works.
