### ISSUE TITLE
Background Menu does not displaying correctly

### ISSUE THREAD

**Issue by gr-maggi** [blackberry/jQueryMobile-BB10-Theme#77]
Hello,

When the application display the menus, the background is not being well displayed, it looks like rectangles. I attached an image to show you how it's being displayed.

![IMG_00000036](https://f.cloud.github.com/assets/2686547/22535/9511c2c0-4a02-11e2-8f03-14aeaa074ccd.png)

**Comment by jasondscott** [comment]
Can you please provide a code sample to recreate this issue.
Please make sure that you are using the latest https://github.com/blackberry/jQueryMobile-BB10-Theme/tree/master/dist/latest . There were updates to the actionbar/overflow menu last week which I think will take care of this issue.

**Comment by jasondscott** [comment]
I can not reproduce. Closing
