### ISSUE TITLE
Action bar links not working

### ISSUE THREAD

**Issue by gr-maggi** [blackberry/jQueryMobile-BB10-Theme#78]
Hello,

I'm trying to use the Action Bar elements as in the demos I found here but the links do not work. Also, I'm having another problem with the Action Bar. When the application display a menu, the Menu Icon disappears and it is not being displayed until I tap another element in the Action Bar.

I attached an image to show you.

![1234](https://f.cloud.github.com/assets/2686547/22554/c1746b32-4a03-11e2-9607-986d668fffcd.jpg)

**Comment by jasondscott** [comment]
Can you please provide a code sample using jsbin or jsfiddle?

Thanks

**Comment by Gerii** [comment]
Do you mean the location link in your actionbar?
You have to wait for the pageinit event before binding the listener. Example is here:
https://github.com/blackberry/jQueryMobile-BB10-Theme/issues/67#issuecomment-11446291

**Comment by itassets** [comment]
@Gerii  have you solved this? i've got the same problem. I've binded click event on action bar items to the $.mobile.changePage and there is also a  $(document).bind( 'pagebeforechange', function()) to populate the contents of the page to be redirected to. Not working at all. The same code in pure jquery mobile is running and actually is an app for BB Playbook.

**Comment by lumierephoto** [comment]
I'm having issues as well with the ActionBar links when they are in the footer as well as when the Tabs are in the Overflow menu. It may work once, but then the UI starts jumping all over the place.

Also, the footer and the back button won't always render correctly if the link is to a page that has a back button and footer. For example, the back button will show up at the bottom right hand corner of the page as a small button and the footer bar won't show up. 

I'm using the code from here:  http://jsbin.com/ojugal/3/edit

**Comment by CarpeTempus** [comment]
Hi there, I've got the same problem, links are not working - but I guess I know the reason: currently I'm using jQuery 1.8.2 and jQuery mobile 1.2.0 in my project and not the BlackBerry-JQM-all.js-File.. could this be the reason?

**Comment by itassets** [comment]
I,Ve tried both and the behaviour was the same. When links work some events like pagebeforechange dont .
I was told to do some changes toi de code but havent done so yet. Will post the results whenever i can

Enviado desde mi BlackBerry de Movistar (http://www.movistar.com.ar) 

-----Original Message-----
