### ISSUE TITLE
Implementing a Context Menu

### ISSUE THREAD

**Issue by ProLove365** [blackberry/jQueryMobile-BB10-Theme#8]
I am trying to implement a Context Menu on the jQuery Mobile BB10 Theme. I am assuming it is a 
special instance of the Action Overflow menu. 

How can I adjust the slide behavior to achieve the two states of the Context Menu without messing 
up the standard definition of the Action Overflow Menu?

What is the user action that enables the narrow Context Menu?

What is the user action that causes the wider Context Menu to appear?

**Comment by jasondscott** [comment]
Hi @ProLove365,

I recommend using the webworks context menu for your application. It has everything you are asking for.
The documentation is available here.
https://developer.blackberry.com/html5/apis/blackberry.ui.contextmenu.html

If you need something more than what the webworks context menu can provide please open a new issue with and we will look into it. 

Thanks

**Comment by ProLove365** [comment]
Jason,

Thank you for your quick response. I appreciate your help on my questions. I am new to developing mobile apps and feel like I keep running into a brick wall. I will look into your recommendation and close this question on the BlackBerry Developer Forums. 

Thanks!
