### ISSUE TITLE
Actionbar data-overflow="true" onClick not working

### ISSUE THREAD

**Issue by PhilipKirkbride** [blackberry/jQueryMobile-BB10-Theme#80]
To simulate this problem open kitchensink/actionbar.html

Add the following javascript to an action div 

onclick="javascript&colon;location.href='index.html'"

If the div doesn't have data-overflow="true" it works.

If it does have data-overflow="true" it doesn't work.

**Comment by PhilipKirkbride** [comment]
I just tried changing the javascript code to an alert and it doesn't work either. 

So I guess any onClick Javascript is not working with data-overflow="true" divs.

**Comment by jasondscott** [comment]
I added `onclick="javascript&colon;location.href='index.html'"` as part of the new sample check it out here, https://github.com/blackberry/jQueryMobile-BB10-Theme/blob/master/kitchenSink/actionbar_sample.html
