### ISSUE TITLE
Dialog and several transitions show actionbar overflowMenu

### ISSUE THREAD

**Issue by nsalyzyn-atimi** [blackberry/jQueryMobile-BB10-Theme#82]
If there is an actionbar with overflow menu, you can see the overflow menu in many undesirable situations.
1. For example, if you do a 'swipeup' page transition, the overflow menu is completely visible while the page fades out.
2. Another example, is if you do a pagechange using {role : 'dialog'}, the overflow menu is shown.
I've seen it as an artifact in a few other locations, but these two are most problematic.

**Comment by jasondscott** [comment]
Hi @nsalyzyn-atimi 

Thanks for your post. 

A refactor of the actionbar/overflow menus is being done which should fix this issue. The change should land sometime next week.

**Comment by nsalyzyn-atimi** [comment]
Hi Jason,

Thanks for the heads up.  I was in the middle of writing up an example that demonstrates:
- slow navigation on the overflow menu
- asking how to get an icon selected by default in the overflow menu
- overflow menu stays selected when you touchdown inside and touchup outside
- overflow menu ends up being allowed to scroll left and right
- difficult to scroll the overflow menu since you'll end up selecting an item
- the above issue

Would the example still be valuable to you if you're in the middle of a refactor?  I'm nearly finished creating it.

**Comment by nsalyzyn-atimi** [comment]
I added the sample code and explanations for each of the above in #92. Let me know if you'd like any elaboration.  I'm a bit swamped fixing other bugs in the app we've been working on, but I can close off a bunch of QA concerns if "framework-related" issues like this get resolved.
