### ISSUE TITLE
Internationalizing back-button

### ISSUE THREAD

**Issue by Gerii** [blackberry/jQueryMobile-BB10-Theme#86]
Right now I'm just adding

``` javascript
<div id="backButton" data-role="back" class="action-bar-back">
    <div class="action-bar-back-text">
        <p>Zur&uuml;ck</p>
    </div>
</div>
```

but it would be nice if it just was possible to do something like this:

``` javascript
<div id="backButton" data-role="back">Zur&uuml;ck</div>
```

At least it would be nice if it was mentioned in the docs so that others don't have to search the DOM to find out how to change it.

**Comment by jasondscott** [comment]
You can change it with the default JQM back button options
`$.mobile.page.prototype.options.backBtnText`

You will need to set up the code a little differently however so that you can bind to the `mobileinit` event. Here is how to make it work.

```
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.1/jquery.
<link rel="stylesheet" href="../dist/latest/BlackBerry-JQM.css" />

<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script> 
    $(document).bind("mobileinit", function() {
        $.mobile.page.prototype.options.backBtnText = "Zur&uuml;ck";
    });
</script>
<script src="../dist/latest/BlackBerry-JQM-Init.js"></script>
<script src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script>
<script src="../dist/latest/BlackBerry-JQM.js" type="text/javascript"></script>
```

Thanks agin for the post. 
I will add this to the docs shortly.

**Comment by jasondscott** [comment]
Added Docs a9b0683d056c4d1103f44151b8d989b06e47368c
