### ISSUE TITLE
Resizing input fields...possibly also the drop down lists?

### ISSUE THREAD

**Issue by rherfurth** [blackberry/jQueryMobile-BB10-Theme#87]
I noticed I cannot change the width of input fields -> or not doing it properly?

<input type="text" name="text-input" id="basic" placeholder="Enter Text Here 1"/>

example : Apartment number may only need 4 spaces total, not the entire screen

Also I use two drop down list to pick numbers from 1 to say 50.  This too takes up the whole screen width therefore takes 2 lines...any suggestions on making this fit on one?

**Comment by jasondscott** [comment]
Hi @rherfurth 

You can override these sizes with custom css
Dropdown

```
.ui-collapsible {
    width: 50%;
}
```

Input fields

```
.ui-input-text {
    width: 120px !important;
}
```

Thanks for the post.
