### ISSUE TITLE
Button groups not displaying properly

### ISSUE THREAD

**Issue by rherfurth** [blackberry/jQueryMobile-BB10-Theme#88]
Can't seem to get it to work nicely with http://jsfiddle.net/Srr5y/ => HTML source is here...

When you embed in HTML the controlgroup, they show up nicely as a pair.  However when I generate the controlgroup via javascript, it doesn't.  Copy to HTML to file locally and you will see immediately what I mean....I have embedded CSS and JS required.

**Comment by jasondscott** [comment]
@rherfurth did you get this working?

**Comment by rherfurth** [comment]
Not yet...I think it's something with Javascript.  I have small formatting to do, then my app is done, minus this bug.  I might put in a work around for submission BB10 deadline.
I have a lot of major enhancements I keep adding to my list for the near future, and reviewing BB10 Design Principles I might be dropping this and going another route.
Date: Fri, 4 Jan 2013 12:34:30 -0800
