### ISSUE TITLE
List View that contains LInks

### ISSUE THREAD

**Issue by ProLove365** [blackberry/jQueryMobile-BB10-Theme#9]
In the jQuery Mobile BB10 Theme, I am having a hard time trying to implement what should be a simple visual style on a listview that contains a href.

My app has two types of lists. The normal list (without links) is ok.

The list that contains a href is where my problem is. Both lists look the same and I have no way for the user to easily distinguish between a link and a non-link.

I tried several variations of placing [data-icon="arrow-r"] and [data-icon="ui-icon-arrow-r"] at both the `<ul>` and `<li>` levels.

Should I add and manipulate [class="ui-li-aside"] or [class="ui-li-count"] areas to insert an arrow image?

I know there is an easily solution to this that I am overlooking.

**Comment by jasondscott** [comment]
@ProLove365 It should work as you expected now. If not we can reopen this issue.
