### ISSUE TITLE
Zoom/pan inside Jquery Mobile

### ISSUE THREAD

**Issue by nsalyzyn-atimi** [blackberry/jQueryMobile-BB10-Theme#90]
It is common for apps to have a header and footer and a center area that can be zoomed/panned.  Are there any blackberry 10 specific suggestions related to this? Or should I look into jQuery mobile plugins that imitate this functionality?

**Comment by jasondscott** [comment]
@nsalyzyn-atimi have you considered an iframe for your center area?

**Comment by nsalyzyn-atimi** [comment]
The iframe can get me pan, but not zoom.  I can get pan more easily using a <div> with overflow:scrolling and explicit height/width.  I'm going to try some jquery plugins and see how they behave.

**Comment by jasondscott** [comment]
Is is more a question than an issue. Try posting to the forum instead. http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/bd-p/browser_dev
