### ISSUE TITLE
the overflow action on the action bar does not work

### ISSUE THREAD

**Issue by hkao** [blackberry/jQueryMobile-BB10-Theme#93]
the latest version of Blackberry-JQM-all.js does not work in terms of opening the overflow action on the  action bar

(resolved.  see below).

**Comment by hkao** [comment]
I just realized that the "vclick" has been changed to "touchend" in the actionbar function.  So one needs to run simulator for it to work.

**Comment by jasondscott** [comment]
You can also run it from ripple. Sent from my BlackBerry 10 smartphone.From: hkaoSent: Monday, January 7, 2013 11:34 AMTo: blackberry/jQueryMobile-BB10-ThemeReply To: blackberry/jQueryMobile-BB10-ThemeSubject: Re: [jQueryMobile-BB10-Theme] the overflow action on the action bar
 does not work (#93)I just realized that the "vclick" has been changed to "touchend" in the actionbar function.  So one needs to run simulator for it to work.

```
          —
          Reply to this email directly or view it on GitHub.
```

**Comment by hkao** [comment]
Thanks!
Do you know if the viewport issue will be resolved soon?

Hong

**Comment by jasondscott** [comment]
@hkao Which viewport issue are you referring too?
