### ISSUE TITLE
BB10 JQM Theme renders very large UI in Simulator

### ISSUE THREAD

**Issue by lumierephoto** [blackberry/jQueryMobile-BB10-Theme#95]
Compared to other native apps in the simulator, my BB 10 jQuery Mobile app renders a very large UI. 

My App:

![PCPHOTO_APP](https://f.cloud.github.com/assets/981541/49476/8b4d000e-5963-11e2-861f-7fc1a62c60cf.png)

Native BB 10 App: 

![BB_App](https://f.cloud.github.com/assets/981541/49477/962107b4-5963-11e2-9930-80c7c713a2ee.png)

I've tried looking for a solution online but have not found one.

Also, renders large UI in browser as well.

**Comment by jasondscott** [comment]
You need to remove the meta tag in your html file.

"Important note: The meta tag <meta name="viewport" content="width=device-width, initial-scale=1"> recommended by jQuery Mobile will need to be removed. This is a temporary issue which should be resolved shortly." from https://github.com/blackberry/jQueryMobile-BB10-Theme/blob/master/docs/README.md 

Thanks for the post

**Comment by lumierephoto** [comment]
I assume you mean the meta tag for the viewport.

I removed all meta tags. Including:

```
     <meta charset="UTF-8">
```

I had the viewport rendered via Javascript mentioned on the BB Webworks website. I removed that too.:  

```
var meta = document.createElement("meta");
meta.setAttribute('name','viewport');
meta.setAttribute('content','initial-scale='+ (1/window.devicePixelRatio) + ',user-scalable=no');
document.getElementsByTagName('head')[0].appendChild(meta);
```

Still, the UI is extra large.

**Comment by mdabydeen** [comment]
@lumierephoto are you using this with WebWorks? If so what version of the SDK? I can't reproduce this in the latest SDK release.

**Comment by lumierephoto** [comment]
@mdabydeen Yes, I'm using the latest version of the Webworks SDK. These are screenshots from the simulator,however, the UI renders very large in the browser as well. 

I'm convinced that it has to do with the BB10 jQuery Mobile JS and CSS files because if I switch them out with my original JQM files, it renders normally even when compiled to the simulator. In fact, when I first tested out the SDK and the simulator (last week) I compiled this same app as a test with Phonegap and it rendered almost normally. There were a few rendering issues, but not this scaling issue. 

I am very new to BB development, so I may be wrong.

**Comment by lumierephoto** [comment]
I followed this solution recommended by biggerCC here:  http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/Ripple-vs-Simulator-scale-css-problem/m-p/2053603

BB10 Theme needs a specific viewport. At least this works for me in BB10 simulator.

```
     <meta name="viewport" content="width=720, user-scalable=no, target-densityDpi=160" />
```

![PC_PHOTO_NEW_META](https://f.cloud.github.com/assets/981541/55650/c3a6ee26-5add-11e2-9f73-65a3d07a4af6.png)

Thanks @PawelGorny on the BB forums for leading me in the right direction!
